
name = "trynex-ecommerce"
compatibility_date = "2024-03-18"
pages_build_output_dir = "dist"

[env.production.vars]
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres.uftbaywtpnwdhflujhsb:Azim12345678900@aws-0-ap-southeast-1.pooler.supabase.co:6543/postgres"
SUPABASE_URL = "https://uftbaywtpnwdhflujhsb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdGJheXd0cG53ZGhmbHVqaHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQxNTc0NjgsImV4cCI6MjAzOTczMzQ2OH0.C67BKQW1UnqcC0N4gkcgMRn3oKqgzfYNp3XVK4hG4QY"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdGJheXd0cG53ZGhmbHVqaHNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNDE1NzQ2OCwiZXhwIjoyMDM5NzMzNDY4fQ.vFRhVnxY7hJOW7I1S5SIBZQhJV1O1kOhK8xk9tIhEZQ"

[[env.production.routes]]
pattern = "/api/*"
zone_name = ""

[build]
command = "npm run build"
