# Cloudflare Pages Wrangler Configuration for TryneX eCommerce
name = "trynex-ecommerce"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables for Cloudflare Workers
[env.production]
vars = { ENVIRONMENT = "production" }

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
publish = "dist"

# Environment variables for secure deployment
[[env.production.vars]]
DATABASE_URL = ""
SUPABASE_URL = "https://lxhhgdqfxmeohayceshb.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aGhnZHFmeG1lb2hheWNlc2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTk1OTAsImV4cCI6MjA2OTQ3NTU5MH0.gW9X6igqtpAQKutqb4aEEx0VovEZdMp4Gk_R8Glm9Bw"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4aGhnZHFmeG1lb2hheWNlc2hiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzg5OTU5MCwiZXhwIjoyMDY5NDc1NTkwfQ.zsYuh0P2S97pLrvY6t1j-qw-j-R_-_5QQX7e423dDeU"
JWT_SECRET = "trynex_secret_key_2025"

# Node.js compatibility for API routes
[vars]
ENVIRONMENT = "development"